### ISSUE TITLE
请问能写一下docker的部署代码吗

### ISSUE THREAD

**Issue by despacito008** [fireinrain/javbus-telegram-bot#1]

**Comment by fireinrain** [comment]
你好 已经更新了docker-compose文件 你可以按照说明 使用docker-compose直接启动

**Comment by garyvalue** [comment]
ERROR: Encountered errors while bringing up the project.
customer@s196633:~/javbus-tg-bot$ docker-compose up -d
Starting javbus-tg-bot ... error

ERROR: for javbus-tg-bot  Cannot start service javbus-tg-bot: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/customer/javbus-tg-bot/javbus-tg-bot.db" to rootfs at "/app/javbus-tg-bot.db" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for javbus-tg-bot  Cannot start service javbus-tg-bot: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/customer/javbus-tg-bot/javbus-tg-bot.db" to rootfs at "/app/javbus-tg-bot.db" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
请问这个报错应该怎么处理呀
